### PR TITLE
Change Alef letter to math style

### PR DESCRIPTION
**Pull request by shadinaif**
This is to change the font of the Alef letter from it's original style, to math style

original:
selection_004

New:
selection_003

### CODE REVIEW

**Comment by shadinaif** [comment]
@OmarIthawi would you please take a look here

**Important**: my branch is forked from `omar/sheen-char`

**Comment by OmarIthawi** [comment]
Thanks @shadinaif! Could you please rebase on `master`?

**Comment by shadinaif** [comment]
@OmarIthawi I did that, and it is up-to-date already :)

**Comment by OmarIthawi** [comment]
@shadinaif I don't think so, it still have commits that are in master already. Could you please make sure that you're only including:

 - [@shadinaif ](/shadinaif) [Change Alef letter to math style](/OmarIthawi/amiri/pull/1/commits/cfe8789199b802af861f15a963cf6b3bde4c4d5a) [cfe8789](/OmarIthawi/amiri/pull/1/commits/cfe8789199b802af861f15a963cf6b3bde4c4d5a)

in this PR?

see: https://github.com/OmarIthawi/amiri/pull/2

**Comment by shadinaif** [comment]
Sorry @OmarIthawi  . It is re-based now :)

**Review by OmarIthawi — APPROVED** [review]
LGTM! Thanks @shadinaif!

**Comment by shadinaif** [comment]
Thank you @OmarIthawi :tada:

**Pull request merged**
